# Site settings
author: Gio Zavaglia
title: It's Gio Y'all
header-img: img/home-bg.png
email: gio.zavaglia@gmail.com
copyright_name: Gio Zavaglia
description: > # this means to ignore newlines until "baseurl:"
  "Hello Worlding" since 1989
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gzavaglia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
